apiVersion: v1
kind: Service
metadata:
  labels:
    app: homer
  name: homer-service
  namespace: simpson
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: homer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homer
  name: homer-deployment
  namespace: simpson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homer
        family: simpson
    spec:
      nodeSelector:
        family: "simpson"
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGISTRY_OPENSHIFT_SERVER_ADDR
          value: 127.0.0.1
        image: quay.io/ralvares/container-helper
        command:
          - /bin/bash
          - -c
          - |
            /usr/bin/dockerregistry >/dev/null 2>/dev/null&
            while :
            do
                for dst in marge-service.simpson selma-service.bouvier patty-service.bouvier
                
                do
                _RETURN=$(curl --connect-timeout 3 -o /dev/null -k -i -sL --post302 -w "%{http_code}" "${dst}:5000")
                if [ $_RETURN == "200" ] ;
                then
                    echo "from homer-service.simpson to ${dst} -> OK"
                else 
                    echo "from homer-service.simpson to ${dst} -> FAIL"
                fi
                done
                sleep 10
            done
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30