apiVersion: v1
kind: Service
metadata:
  labels:
    app: homer
  name: homer-service
  namespace: simpson
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: homer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marge
  name: marge-service
  namespace: simpson
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: marge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homer
  name: homer-deployment
  namespace: simpson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homer
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - "/usr/bin/dockerregistry >/dev/null 2>/dev/null&\nwhile :\ndo\n    for dst
          in marge-service.simpson selma-service.bouvier patty-service.bouvier\n    \n
          \   do\n    _RETURN=$(curl -o /dev/null -k -i -sL --post302 -w \"%{http_code}\"
          \"${dst}:5000\")\n    if [ $_RETURN == \"200\" ] ;\n    then\n        echo
          \"from homer-service.simpson to ${dst} -> OK\"\n    else \n        echo
          \"from homer-service.simpson to ${dst} -> FAIL\"\n    fi\n    done\n    sleep
          60\ndone\n"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGISTRY_OPENSHIFT_SERVER_ADDR
          value: 127.0.0.1
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8901f71be47872f0346e8461f3f78f7e84fa6d8affabf70ef1e428442cce9c35
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: marge
  name: marge-deployment
  namespace: simpson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marge
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - "/usr/bin/dockerregistry >/dev/null 2>/dev/null&\nwhile :\ndo\n    for dst
          in homer-service.simpson selma-service.bouvier patty-service.bouvier\n    \n
          \   do\n    _RETURN=$(curl -o /dev/null -k -i -sL --post302 -w \"%{http_code}\"
          \"${dst}:5000\")\n    if [ $_RETURN == \"200\" ] ;\n    then\n        echo
          \"from marge-service.simpson to ${dst} -> OK\"\n    else \n        echo
          \"from marge-service.simpson to ${dst} -> FAIL\"\n    fi\n    done\n    sleep
          60\ndone\n"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGISTRY_OPENSHIFT_SERVER_ADDR
          value: 127.0.0.1
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8901f71be47872f0346e8461f3f78f7e84fa6d8affabf70ef1e428442cce9c35
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: homer
  name: homer-web
  namespace: simpson
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: homer-service
    weight: 100
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: marge
  name: marge-web
  namespace: simpson
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: marge-service
    weight: 100
