apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SI System and Information Integrity
    policy.open-cluster-management.io/controls: SI-5 Security Alerts Advisories and
      Directives
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: policy-acs-central-ca-bundle
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-acs-central-ca-bundle
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: stackrox
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              annotations:
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              name: create-cluster-init
              namespace: stackrox
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              annotations:
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                argocd.argoproj.io/sync-wave: "1"
              name: create-cluster-init
              namespace: stackrox
            rules:
            - apiGroups:
              - ""
              resources:
              - secrets
              verbs:
              - get
              - list
              - create
              - patch
              - update
            - apiGroups:
              - platform.stackrox.io
              resources:
              - securedclusters
              verbs:
              - get
              - list
              - patch
              - update
            - apiGroups:
              - route.openshift.io
              resources:
              - routes
              verbs:
              - get
              - list
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              annotations:
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              name: create-cluster-init
              namespace: stackrox
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: Role
              name: create-cluster-init
            subjects:
            - kind: ServiceAccount
              name: create-cluster-init
              namespace: stackrox
        - complianceType: musthave
          objectDefinition:
            apiVersion: batch/v1
            kind: Job
            metadata:
              annotations:
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                argocd.argoproj.io/sync-wave: "2"
              name: create-cluster-init-bundle
              namespace: stackrox
            spec:
              template:
                metadata:
                  annotations:
                    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                spec:
                  containers:
                  - command:
                    - /bin/bash
                    - -c
                    - |
                      #!/usr/bin/env bash
                      if kubectl get secret/sensor-tls &> /dev/policies; then
                        echo "cluster-init bundle has already been configured, doing nothing"
                        exit 0
                      else

                        # Wait for central to be ready
                        attempt_counter=0
                        max_attempts=50
                        echo "Waiting for central to be available..."
                        until $(curl -k --output /dev/policies --silent --head --fail https://central); do
                            if [ ${attempt_counter} -eq ${max_attempts} ];then
                              echo "Max attempts reached"
                              exit 1
                            fi

                            printf '.'
                            attempt_counter=$(($attempt_counter+1))
                            echo "Made attempt $attempt_counter, waiting..."
                            sleep 5
                        done

                        echo "Configuring cluster-init bundle"
                        export DATA={\"name\":\"local-cluster\"}
                        curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA https://central/v1/cluster-init/init-bundles

                        echo "Bundle received"
                        cat /tmp/bundle.json

                        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
                            BASE='base64 -w 0'
                        elif [[ "$OSTYPE" == "darwin"* ]]; then
                            BASE='base64'
                        fi

                        echo "Applying bundle"
                        # No jq in container, python to the rescue
                        cat /tmp/bundle.json | python3 -c "import sys, json; print(json.load(sys.stdin)['kubectlBundle'])" | ${BASE} -d | oc apply -f -
                        # Touch SecuredCluster to force operator to reconcile
                        oc label SecuredCluster local-cluster cluster-init-job-status=created
                        ACS_HOST="$(oc get route central -o custom-columns=HOST:.spec.host --no-headers):443"
                        oc patch secret sensor-tls --type='json' -p="[{\"op\" : \"add\", \"path\" : \"/data/acs-host\", \"value\" : \"$(echo $ACS_HOST | ${BASE})\"}]"

                        echo "ACS Cluster init bundle generated and applied"
                      fi
                    env:
                    - name: PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: password
                          name: central-htpasswd
                    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5cb8eed4d9713a7a3da331026e21773c76d52feef9a591921807ccf217f66757
                    imagePullPolicy: Always
                    name: create-cluster-init-bundle
                  dnsPolicy: ClusterFirst
                  restartPolicy: Never
                  serviceAccount: create-cluster-init
                  serviceAccountName: create-cluster-init
                  terminationGracePeriodSeconds: 30
        - complianceType: musthave
          objectDefinition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: SecuredCluster
            metadata:
              name: stackrox-secured-cluster-services
              namespace: stackrox
            spec:
              admissionControl:
                listenOnCreates: false
                listenOnEvents: true
                listenOnUpdates: false
              auditLogs:
                collection: Auto
              centralEndpoint: |
                {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
              clusterName: |
                {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
              perNode:
                collector:
                  collection: KernelModule
                  imageFlavor: Regular
                taintToleration: TolerateTaints
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              admission-control-cert.pem: '{{ fromSecret "stackrox" "admission-control-tls"
                "admission-control-cert.pem" }}'
              admission-control-key.pem: '{{ fromSecret "stackrox" "admission-control-tls"
                "admission-control-key.pem" }}'
              ca.pem: '{{ fromSecret "stackrox" "admission-control-tls" "ca.pem" }}'
            kind: Secret
            metadata:
              name: admission-control-tls
              namespace: policies
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              ca.pem: '{{ fromSecret "stackrox" "collector-tls" "ca.pem" }}'
              collector-cert.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-cert.pem"
                }}'
              collector-key.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-key.pem"
                }}'
            kind: Secret
            metadata:
              name: collector-tls
              namespace: policies
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              acs-host: '{{ fromSecret "stackrox" "sensor-tls" "acs-host" }}'
              ca.pem: '{{ fromSecret "stackrox" "sensor-tls" "ca.pem" }}'
              sensor-cert.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-cert.pem"
                }}'
              sensor-key.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-key.pem"
                }}'
            kind: Secret
            metadata:
              name: sensor-tls
              namespace: policies
            type: Opaque
        remediationAction: enforce
        severity: medium
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-central-ca-bundle
  namespace: policies
placementRef:
  name: placement-policy-acs-central-ca-bundle
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-acs-central-ca-bundle
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-acs-central-ca-bundle
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster