apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ned
  name: ned-deployment
  namespace: flanders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ned
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ned
        family: flanders
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: centos/httpd-24-centos7
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30