apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-1 SYSTEM AND COMMUNICATIONS PROTECTION
      POLICY AND PROCEDURES
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-hardening
  name: policy-remove-kubeadmin
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-remove-kubeadmin
      spec:
        object-templates:
        - complianceType: mustnothave
          objectDefinition:
            kind: Secret
            metadata:
              name: kubeadmin
              namespace: kube-system
            type: Opaque
        remediationAction: inform
        severity: medium
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-remove-kubeadmin
  namespace: policies
placementRef:
  name: placement-policy-remove-kubeadmin
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-remove-kubeadmin
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-remove-kubeadmin
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - spoke03