apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-28 Protection Of Information At
      Rest
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-hardening
  name: policy-file-integrity-node-status
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-file-integrity-node-status
      spec:
        object-templates:
        - complianceType: mustnothave
          objectDefinition:
            apiVersion: fileintegrity.openshift.io/v1alpha1
            kind: FileIntegrityNodeStatus
            metadata:
              namespace: openshift-file-integrity
            results:
            - condition: Failed
        remediationAction: inform
        severity: medium
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-file-integrity-node-status
  namespace: policies
placementRef:
  name: placement-policy-file-integrity-node-status
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-file-integrity-node-status
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-file-integrity-node-status
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - prod