apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-4 Information In Shared Resources
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-hardening
  name: policy-scc-restricted
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-scc-restricted
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            allowHostDirVolumePlugin: false
            allowHostIPC: false
            allowHostNetwork: false
            allowHostPID: false
            allowHostPorts: false
            allowPrivilegeEscalation: true
            allowPrivilegedContainer: false
            allowedCapabilities: null
            apiVersion: security.openshift.io/v1
            defaultAddCapabilities: null
            fsGroup:
              type: MustRunAs
            groups:
            - system:authenticated
            kind: SecurityContextConstraints
            metadata:
              annotations:
                include.release.openshift.io/ibm-cloud-managed: "true"
                include.release.openshift.io/self-managed-high-availability: "true"
                include.release.openshift.io/single-node-developer: "true"
                kubernetes.io/description: restricted denies access to all host features
                  and requires pods to be run with a UID, and SELinux context that
                  are allocated to the namespace.  This is the most restrictive SCC
                  and it is used by default for authenticated users.
                release.openshift.io/create-only: "true"
              name: restricted
            priority: null
            readOnlyRootFilesystem: false
            requiredDropCapabilities:
            - KILL
            - MKNOD
            - SETUID
            - SETGID
            runAsUser:
              type: MustRunAsRange
            seLinuxContext:
              type: MustRunAs
            supplementalGroups:
              type: RunAsAny
            users: []
            volumes:
            - configMap
            - downwardAPI
            - emptyDir
            - persistentVolumeClaim
            - projected
            - secret
        remediationAction: inform
        severity: medium
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-scc-restricted
  namespace: policies
placementRef:
  name: placement-policy-scc-restricted
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-scc-restricted
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-scc-restricted
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - prod