kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: bouvier
  labels:
    house: bouvier
  annotations:
    openshift.io/node-selector: "house=bouvier"
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "house", "Operator":"Equal", "Value": "bouvier", "effect": "NoSchedule"}]'