apiVersion: v1
data:
  container-helper.yaml: |+
    ---
    response: "Selma"
    tcpchecks:
      - name: marge.simpson
        host: marge-service.simpson
        port: 8080
      - name: homer.simpson
        host: homer-service.simpson
        port: 8080
      - name: patty.bouvier
        host: patty-service.bouvier
        port: 8080

kind: ConfigMap
metadata:
  labels:
    app: selma
  name: selma-container-helper
  namespace: bouvier
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: selma
  name: selma-service
  namespace: bouvier
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: selma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selma
  name: selma-deployment
  namespace: bouvier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selma
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selma
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/ralvares/container-helper:minimal
        imagePullPolicy: Always
        name: container-helper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /container-helper/
          name: container-helper-yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: selma-container-helper
        name: container-helper-yaml
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: selma
  name: selma-web
  namespace: bouvier
spec:
  host: selma.bouvier.ocp.example.local
  port:
    targetPort: 8080
  to:
    kind: Service
    name: selma-service
    weight: 100
