apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SI System and Information Integrity
    policy.open-cluster-management.io/controls: SI-5 Security Alerts Advisories and
      Directives
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: policy-advanced-managed-cluster-security
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-advanced-managed-cluster-security
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: stackrox
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: rhacs-operator
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: rhacs-operator-group
              namespace: rhacs-operator
            spec: {}
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: rhacs-operator
              namespace: rhacs-operator
            spec:
              channel: latest
              installPlanApproval: Automatic
              name: rhacs-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              admission-control-cert.pem: '{{ fromSecret "stackrox" "admission-control-tls"
                "admission-control-cert.pem" }}'
              admission-control-key.pem: '{{ fromSecret "stackrox" "admission-control-tls"
                "admission-control-key.pem" }}'
              ca.pem: '{{ fromSecret "stackrox" "admission-control-tls" "ca.pem"
                }}'
            kind: Secret
            metadata:
              name: admission-control-tls
              namespace: stackrox
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              ca.pem: '{{ fromSecret "stackrox" "collector-tls" "ca.pem" }}'
              collector-cert.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-cert.pem"
                }}'
              collector-key.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-key.pem"
                }}'
            kind: Secret
            metadata:
              name: collector-tls
              namespace: stackrox
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            data:
              acs-host: '{{ fromSecret "stackrox" "sensor-tls" "acs-host" }}'
              ca.pem: '{{ fromSecret "stackrox" "sensor-tls" "ca.pem" }}'
              sensor-cert.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-cert.pem"
                }}'
              sensor-key.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-key.pem"
                }}'
            kind: Secret
            metadata:
              name: sensor-tls
              namespace: stackrox
            type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: SecuredCluster
            metadata:
              name: stackrox-secured-cluster-services
              namespace: stackrox
            spec:
              admissionControl:
                listenOnCreates: false
                listenOnEvents: true
                listenOnUpdates: false
              auditLogs:
                collection: Auto
              centralEndpoint: |
                {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
              clusterName: |
                {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
              perNode:
                collector:
                  collection: KernelModule
                  imageFlavor: Regular
                taintToleration: TolerateTaints
        remediationAction: enforce
        severity: medium
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-advanced-managed-cluster-security
  namespace: policies
placementRef:
  name: placement-policy-advanced-managed-cluster-security
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-advanced-managed-cluster-security
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-advanced-managed-cluster-security
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - "OpenShift"